from . import product
from . import sale_order
from . import purchase_order
from . import stock_move_line
from . import stock_quant
from . import account_invoice
from . import SupplierDiscount
from . import res_partner
from . import stock_production_lot
from . import stock_inventory
from . import res_config_setting
from . import intrastat_product_declaration
from . import stock_picking